<a href="https://colab.research.google.com/github/yaki2022/yaki2022/blob/main/Matrices_G_46.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Creacion de matrices

matrix=[[23,7,42],[2,3,4],[87,45,21]]
print(matrix)

x=matrix[1][2]


print(x)




[[23, 7, 42], [90, [2, 3, 4], 32], [87, 45, 21]]
32



##Crear unua matriz de 7x7 con valores libres, y presentar extraer en una lista las siguientes posiciones en el siguiente orden
(4,0)-(6,3)-(5,2)-(0,3)-(0,0)-(1,0)-(3,2)










## Ingreso de matrices por ciclos

In [ ]:


pos00=int(input("ingrese el primer valor: "))
pos01=int(input("ingrese el segundo valor: "))
pos10=int(input("ingrese el tercer valor: "))
pos11=int(input("ingrese el cuarto valor: "))

matris=[[pos00,pos01],[pos10,pos11]]
#4print(matris)
for i in matris:
 print(i)


ingrese el primer valor: 100
ingrese el segundo valor: 200
ingrese el tercer valor: 4
ingrese el cuarto valor: 5
[100, 200]
[4, 5]


2

# llenado por ciclos

In [ ]:
fila1=[0,0,0,0,0,0,0,0]
for i in range(8):
  fila1[i]="hola"
  print(fila1)
  

['hola', 0, 0, 0, 0, 0, 0, 0]
['hola', 'hola', 0, 0, 0, 0, 0, 0]
['hola', 'hola', 'hola', 0, 0, 0, 0, 0]
['hola', 'hola', 'hola', 'hola', 0, 0, 0, 0]
['hola', 'hola', 'hola', 'hola', 'hola', 0, 0, 0]
['hola', 'hola', 'hola', 'hola', 'hola', 'hola', 0, 0]
['hola', 'hola', 'hola', 'hola', 'hola', 'hola', 'hola', 0]
['hola', 'hola', 'hola', 'hola', 'hola', 'hola', 'hola', 'hola']


#ciclo for anidado

In [ ]:
matis=[[0,0,0],[0,0,0],[0,0,0]]

for i in range(3):
   for j in range(3):
     matis[j][i]=100
#print(matis)

for t in matis:
  print(t)
     



[100, 100, 100]
[100, 100, 100]
[100, 100, 100]


#Comoando par obtener solo una parte de la matriz

In [ ]:
matriz=[[3,4,10,23],[90,80,4,4],[23,45,21,1],[13,14,110,213],[910,180,14,14],[232,425,221,12]]

print(matriz[4:6]) # corta la matriz desde la fila 1 a la fila 3


print("_____________________________--")
for i in matriz:
  print(i)

[[910, 180, 14, 14], [232, 425, 221, 12]]
_____________________________--
[3, 4, 10, 23]
[90, 80, 4, 4]
[23, 45, 21, 1]
[13, 14, 110, 213]
[910, 180, 14, 14]
[232, 425, 221, 12]


#Numpy (crear matrices en ceros 45x45)

In [ ]:
import numpy
import random

a = numpy.ones((4,4))

#Random 0 aleatorio  genera numeros aleatoreos en un rango 
x=random.randrange(23,26)
print(x)
#for i in a :
 # print(i)


23


## JUEGO DEL BUSCAMINAS

In [ ]:
import numpy

fallo=0
puntos=0
tablero=numpy.zeros((8,8))


for i in range(8):
   for j in range(8):
     tablero[i][j]=random.randrange(0,2)
print(tablero)

print("***BUSCA MINAS *****")
print("Ingrese las coordenadas donde creas que no hay mina")

while fallo!=5 and puntos!=5:
  filas=int(input("Ingrese la fila:  "))
  columna=int(input("Ingrese la columna:  "))

  if tablero[filas][columna]==1:
    fallo=fallo+1
    print("caiste en una mina BOOOOMMMM  :(    ")
    print("minas encontradas: ",fallo,"puntos: ",puntos)
  else:
    puntos=puntos+1
    print("muy bien casilla sin minas :) ")
    print("minas encontradas: ",fallo,"puntos: ",puntos)
    

  if fallo==3:
    print("PERDISTE EL JUEGO ")
  if puntos==3:
    print("Felicidades Ganaste el Juego")

print ("Gracias por jugar")




[[1. 0. 1. 1. 1. 0. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0. 1. 1.]
 [1. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 1. 1. 1. 1.]]
***BUSCA MINAS *****
Ingrese las coordenadas donde creas que no hay mina
Ingrese la fila:  2
Ingrese la columna:  3
muy bien casilla sin minas :) 
minas encontradas:  0 puntos:  1
Ingrese la fila:  4
Ingrese la columna:  1
muy bien casilla sin minas :) 
minas encontradas:  0 puntos:  2
Ingrese la fila:  0
Ingrese la columna:  1
muy bien casilla sin minas :) 
minas encontradas:  0 puntos:  3
Felicidades Ganaste el Juego
Ingrese la fila:  4
Ingrese la columna:  2
muy bien casilla sin minas :) 
minas encontradas:  0 puntos:  4
Ingrese la fila:  5
Ingrese la columna:  0
caiste en una mina BOOOOMMMM  :(    
minas encontradas:  1 puntos:  4
Ingrese la fila:  2
Ingrese la columna:  6
muy bien casilla sin minas :) 
minas encontradas:  1 puntos:  5
Gracias por jugar


1
1
0
[[1, 1, 0], [1, 1, 0], [1, 1, 0]]
En que posiscion cres que no haya bomba
ingrese la fila: 1
ingrese la columnas: 1
Caiste :( BOOM  lo siento
fallos= 1
puntos= 0
0
0
1
[[0, 0, 1], [0, 0, 1], [0, 0, 1]]
En que posiscion cres que no haya bomba
ingrese la fila: 2
ingrese la columnas: 1
Te salvaste en 2 , 1 no hay bomba
fallos= 1
puntos= 1
0
0
1
[[0, 0, 1], [0, 0, 1], [0, 0, 1]]
En que posiscion cres que no haya bomba
ingrese la fila: 1
ingrese la columnas: 1
Te salvaste en 1 , 1 no hay bomba
fallos= 1
puntos= 2
1
0
1
[[1, 0, 1], [1, 0, 1], [1, 0, 1]]
En que posiscion cres que no haya bomba
ingrese la fila: 1
ingrese la columnas: 1
Te salvaste en 1 , 1 no hay bomba
fallos= 1
puntos= 3
1
0
0
[[1, 0, 0], [1, 0, 0], [1, 0, 0]]
En que posiscion cres que no haya bomba
ingrese la fila: 1
ingrese la columnas: 2
Te salvaste en 1 , 2 no hay bomba
fallos= 1
puntos= 4
0
1
0
[[0, 1, 0], [0, 1, 0], [0, 1, 0]]
En que posiscion cres que no haya bomba
ingrese la fila: 1
ingrese la columnas: 2
Te sal

#Generar una matriz de 4X4